"""add title and description to call_analysis

Revision ID: 0cc3c0c8515a
Revises: fdab4a37b63f
Create Date: 2026-06-17 17:40:39.265130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc3c0c8515a'
down_revision: Union[str, Sequence[str], None] = 'fdab4a37b63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_analysis', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('call_analysis', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_analysis', 'description')
    op.drop_column('call_analysis', 'title')
    # ### end Alembic commands ###
