"""add_personalisation_notes_to_outreach_execution_log

Revision ID: 1b2c3d4e5f6g
Revises: e6f0891ed4bc
Create Date: 2026-06-23 16:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2c3d4e5f6g'
down_revision: Union[str, Sequence[str], None] = 'e6f0891ed4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreach_execution_log', sa.Column('personalisation_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outreach_execution_log', 'personalisation_notes')
    # ### end Alembic commands ###
