"""add_outreach_execution_log

Revision ID: e6f0891ed4bc
Revises: 0cc3c0c8515a
Create Date: 2026-06-23 16:07:53.009076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f0891ed4bc'
down_revision: Union[str, Sequence[str], None] = '0cc3c0c8515a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('outreach_message_id', sa.Integer(), nullable=True),
    sa.Column('agent_reasoning', sa.Text(), nullable=True),
    sa.Column('chosen_channel', sa.String(length=50), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['outreach_message_id'], ['outreach_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach_execution_log')
    # ### end Alembic commands ###
