"""add call_analysis table

Revision ID: fdab4a37b63f
Revises: 01fb8b216a7b
Create Date: 2026-06-17 15:56:05.059505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdab4a37b63f'
down_revision: Union[str, Sequence[str], None] = '01fb8b216a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('competitors', sa.Text(), nullable=True),
    sa.Column('budget_signals', sa.Text(), nullable=True),
    sa.Column('decision_timeline', sa.Text(), nullable=True),
    sa.Column('buying_intent_score', sa.Float(), nullable=True),
    sa.Column('recommended_follow_up', sa.Text(), nullable=True),
    sa.Column('crm_note', sa.Text(), nullable=True),
    sa.Column('follow_up_email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_analysis')
    # ### end Alembic commands ###
