SEED_LEADS = [
    {
        "first_name": "Michael",
        "last_name": "Hartley",
        "email": "michael.hartley@apexridgereit.com",
        "company": "Apex Ridge Residential REIT",
        "job_title": "VP of Operations",
        "phone": "+1-212-555-0114",
        "city": "New York",
        "state": "NY",
        "country": "United States",
        "status": "new",
        "notes": "Oversees 22,000 units across 18 markets for a publicly traded multifamily REIT. Currently on RealPage Voyager but the reporting module has been generating incorrect occupancy data for six months — RealPage support has been unresponsive. Asset management committee is blocked on quarterly reporting until this is resolved. Evaluating an AI intelligence layer that can pull clean leasing data independently of RealPage's reporting stack. Has executive budget authority up to $50K annually and wants to move quickly given the reporting crisis.",
    },
    {
        "first_name": "Jessica",
        "last_name": "Alvarez",
        "email": "jessica.alvarez@lonestarlivingtx.com",
        "company": "Lone Star Living",
        "job_title": "Director of Leasing",
        "phone": "+1-512-555-0237",
        "city": "Austin",
        "state": "TX",
        "country": "United States",
        "status": "new",
        "notes": "Manages leasing across 5,200 units in Austin and San Antonio. Team of eight leasing reps handles all lead follow-up manually via email — average response time is over four hours. Mentioned losing deals to competitors who respond within minutes. Saw a competing property advertise AI-powered instant follow-up and it accelerated her evaluation. Ready to run a pilot on two Austin properties within 60 days. Budget is not a blocker, she has departmental authority for software under $2,000/month.",
    },
    {
        "first_name": "Ryan",
        "last_name": "Nakamura",
        "email": "ryan.nakamura@meridianproptech.com",
        "company": "Meridian PropTech Partners",
        "job_title": "Chief Technology Officer",
        "phone": "+1-212-555-0358",
        "city": "New York",
        "state": "NY",
        "country": "United States",
        "status": "new",
        "notes": "CTO at a tech-native multifamily operator running 4,800 units on Yardi Voyager with custom API integrations. Running a formal AI vendor evaluation in Q3 across leasing automation, resident communication, and renewal outreach. Previous evaluation with Hyly.AI fell through due to poor Yardi API coverage — middleware dependency was a dealbreaker. Requires native Yardi integration with no middleware layer. Deep technical buyer — will want to review API documentation, data flow diagrams, and field mapping before committing. Q3 evaluation window closes end of September.",
    },
    {
        "first_name": "Sandra",
        "last_name": "Okafor",
        "email": "sandra.okafor@belmontresidential.com",
        "company": "Belmont Residential Group",
        "job_title": "Head of Revenue Management",
        "phone": "+1-404-555-0471",
        "city": "Atlanta",
        "state": "GA",
        "country": "United States",
        "status": "new",
        "notes": "Manages revenue strategy across 8,300 units in Georgia and South Carolina. Renewal conversion rate dropped from 57% to 51% over the past 18 months. Root cause analysis identified inconsistent renewal outreach — some properties reach out at 90 days before expiration, others never contact residents proactively. Wants an automated renewal sequence triggered by Yardi lease expiration data with personalized messaging at scale. Currently tracking renewal intent manually in a shared Google Sheet. Urgency is moderate — board presentation on retention strategy in Q4.",
    },
    {
        "first_name": "Thomas",
        "last_name": "Reeves",
        "email": "thomas.reeves@continentalresidential.com",
        "company": "Continental Residential Holdings",
        "job_title": "VP of Property Technology",
        "phone": "+1-312-555-0582",
        "city": "Chicago",
        "state": "IL",
        "country": "United States",
        "status": "new",
        "notes": "Enterprise operator with 18,500 units, all on Yardi Voyager across 12 markets. Integration-first evaluation criteria — any AI vendor must pass their internal Yardi certification review before moving to commercial discussion. Previous AI vendor (Funnel Leasing) failed the certification review due to write-back permission requirements. Wants to confirm native Yardi API capability, bidirectional sync, and zero middleware dependency before scheduling a demo. IT procurement timeline is 90 days from vendor approval. Legal requires MSA review before any pilot.",
    },
    {
        "first_name": "Ashley",
        "last_name": "Morgan",
        "email": "ashley.morgan@campusedgestudent.com",
        "company": "Campus Edge Student Housing",
        "job_title": "Director of Operations",
        "phone": "+1-512-555-0693",
        "city": "Austin",
        "state": "TX",
        "country": "United States",
        "status": "new",
        "notes": "Operates 6,000 beds across 14 university markets with near 85% annual turnover creating constant re-leasing pressure. Pre-leasing for next academic year starts in November, which is only five months away. Currently using RealPage student module but the communication automation capabilities are inadequate for personalized outreach at this volume. Looking for a supplemental AI layer that can generate personalized renewal and new-lease outreach segmented by bed type, floorplan, and roommate preference. Team is lean — three regional ops managers covering 14 sites.",
    },
    {
        "first_name": "Derek",
        "last_name": "Washington",
        "email": "derek.washington@sunstatemultifamily.com",
        "company": "SunState Multifamily Partners",
        "job_title": "SVP of Leasing",
        "phone": "+1-602-555-0714",
        "city": "Phoenix",
        "state": "AZ",
        "country": "United States",
        "status": "new",
        "notes": "Sun Belt operator with 12,000 units in Phoenix, Las Vegas, and Dallas, actively acquiring to reach 17,000 units by year-end. Leasing team scaling from 20 to 35 reps across the next two quarters. New rep onboarding is taking 6+ weeks with no standardized playbook. Quality of outreach varies widely across reps and markets. Wants AI to standardize leasing workflows, enforce brand-consistent outreach templates, and track performance across new hires from day one. Urgency is high — next acquisition closes in 45 days and new properties need to be leasing-ready immediately.",
    },
    {
        "first_name": "Brenda",
        "last_name": "Simmons",
        "email": "brenda.simmons@newhorizonshousing.org",
        "company": "New Horizons Housing Foundation",
        "job_title": "Property Management Director",
        "phone": "+1-312-555-0825",
        "city": "Chicago",
        "state": "IL",
        "country": "United States",
        "status": "new",
        "notes": "Nonprofit managing 2,800 affordable units under HUD compliance. Recently awarded a $45,000 JPMorgan Chase PRO Neighborhoods technology grant specifically for PropTech adoption. Grant must be spent by Q2 next year. Evaluating AI-assisted leasing communication as the primary use case — income-qualified applicant follow-up is consuming over 40% of staff capacity. Mentioned she has seen other affordable housing operators use AI for document request automation and wants to replicate that. Implementation timeline is grant-driven: go-live by March.",
    },
    {
        "first_name": "Patrick",
        "last_name": "Donnelly",
        "email": "patrick.donnelly@greenviewpm.com",
        "company": "Greenview Property Management",
        "job_title": "Chief Operating Officer",
        "phone": "+1-615-555-0936",
        "city": "Nashville",
        "state": "TN",
        "country": "United States",
        "status": "new",
        "notes": "Mid-size operator with 3,100 units in Nashville and Knoxville. Moved from Excel-based lead tracking to HubSpot eight months ago. HubSpot is set up and clean but no automation sequences are running — they are using it as a glorified contact database. COO is ready to layer AI-generated outreach and lead scoring on top of the existing CRM investment without replacing it. Budget range is $1,500 to $2,500 per month. Decision timeline is this quarter — he has CEO sign-off already. HubSpot-native integration is a requirement.",
    },
    {
        "first_name": "Valeria",
        "last_name": "Cruz",
        "email": "valeria.cruz@pinnacleurbanliving.com",
        "company": "Pinnacle Urban Living",
        "job_title": "Head of Resident Experience",
        "phone": "+1-305-555-0147",
        "city": "Miami",
        "state": "FL",
        "country": "United States",
        "status": "new",
        "notes": "Manages resident experience across 5,500 units in South Florida urban markets. NPS score is 38, below the industry benchmark of 45. Resident communication is inconsistent across the portfolio — maintenance updates, renewal notices, and move-in communications vary by site manager. Looking for an AI layer that can generate personalized resident touchpoints at scale while preserving brand voice. Particularly interested in automated renewal outreach that references the resident's specific unit, lease term, and community history. Willing to pilot on three Miami properties.",
    },
    {
        "first_name": "Garrett",
        "last_name": "Ellison",
        "email": "garrett.ellison@terrabrookbtr.com",
        "company": "Terrabrook BTR Partners",
        "job_title": "VP of Growth",
        "phone": "+1-214-555-0268",
        "city": "Dallas",
        "state": "TX",
        "country": "United States",
        "status": "new",
        "notes": "Build-to-rent operator with 1,800 units in DFW, expanding to 4,000 by end of next year. Modern tech stack: Entrata PMS, Salesforce CRM, CoStar and Apartments.com for leads. No AI tooling yet — the team has been handling everything manually as they scaled. VP sees AI leasing automation as a competitive differentiator in the BTR market where speed-to-lease matters more than multifamily. Budget approved for an AI vendor in H2 — pilot program can start immediately. Wants Entrata-native integration and Salesforce sync. Ready to move fast.",
    },
    {
        "first_name": "Harrison",
        "last_name": "Webb",
        "email": "harrison.webb@coastlinereit.com",
        "company": "Coastline REIT",
        "job_title": "Director of Asset Management",
        "phone": "+1-212-555-0379",
        "city": "New York",
        "state": "NY",
        "country": "United States",
        "status": "new",
        "notes": "REIT with 9,800 units across NYC, Boston, and Miami. Asset management director evaluates all technology on a direct NOI impact basis — a 2% improvement in occupancy adds approximately $4.2M annually across the portfolio. Requested case studies showing lead-to-lease conversion improvement from comparable REITs before scheduling a demo. Decision process goes through an investment committee and requires a formal business case with documented ROI methodology. Evaluation timeline is Q4 with a decision in January. SOC 2 Type II certification is a hard requirement.",
    },
    {
        "first_name": "Crystal",
        "last_name": "Nguyen",
        "email": "crystal.nguyen@summitgateresidential.com",
        "company": "Summit Gate Residential",
        "job_title": "Leasing Operations Manager",
        "phone": "+1-720-555-0481",
        "city": "Denver",
        "state": "CO",
        "country": "United States",
        "status": "new",
        "notes": "Hands-on technical buyer managing leasing operations for 2,600 units across three Denver-area communities. Already evaluated Funnel Leasing and Knock — found both overpriced for their portfolio size. Looking for a right-sized AI leasing solution under $1,000/month. Wants to run a free trial before committing to any commercial terms. Will do the integration setup herself and expects good documentation. Specifically mentioned interest in AI-generated first-touch emails and lead scoring. Makes the recommendation to her VP, who has final sign-off.",
    },
    {
        "first_name": "Olivia",
        "last_name": "Stern",
        "email": "olivia.stern@urbancommonsliving.com",
        "company": "Urban Commons Living",
        "job_title": "VP of Marketing",
        "phone": "+1-310-555-0592",
        "city": "Los Angeles",
        "state": "CA",
        "country": "United States",
        "status": "new",
        "notes": "Marketing VP overseeing 7,200 units across LA, Orange County, and San Diego. Email open rates on resident and prospect outreach are at 12%, well below the 20% industry benchmark. Believes the root cause is generic outreach templates that do not reference unit-specific or neighborhood-specific details. Exploring AI-generated outreach that personalizes messaging based on lead preferences, unit type, and community amenities. Manages a $2M annual marketing budget. Decision timeline is 60 days — wants to have a solution in place before peak spring leasing season.",
    },
    {
        "first_name": "Franklin",
        "last_name": "Torres",
        "email": "franklin.torres@sunriseseniorgroup.com",
        "company": "Sunrise Senior Communities",
        "job_title": "Chief Operating Officer",
        "phone": "+1-704-555-0613",
        "city": "Charlotte",
        "state": "NC",
        "country": "United States",
        "status": "new",
        "notes": "Senior living operator with 3,200 units across 22 communities. Family inquiry volume is high but move-in conversion is low — families typically inquire at three to five communities before making a decision. Current follow-up relies on individual community managers with no standardization or automation. COO drew direct parallels between senior living lead management and multifamily during discovery. Interested in AI that can generate empathetic, family-facing outreach drafts that a community manager reviews before sending. Has full decision authority and a Q3 evaluation window.",
    },
    {
        "first_name": "Nicole",
        "last_name": "Hartman",
        "email": "nicole.hartman@helixpropertygroup.com",
        "company": "Helix Property Group",
        "job_title": "Director of Business Development",
        "phone": "+1-206-555-0724",
        "city": "Seattle",
        "state": "WA",
        "country": "United States",
        "status": "new",
        "notes": "Third-party PM firm currently managing 4,100 units with an active growth plan to 7,000 by 2026. Business development director is building a technology pitch for prospective owner-client relationships. Wants to demonstrate AI-enhanced leasing capabilities as a differentiator when presenting to property owners. Evaluating Domino AI as a capability to include in owner-facing materials and live demos. Decision is driven by business development ROI, not operational pain. Needs proof that the AI output quality is high enough to show in a polished client presentation.",
    },
    {
        "first_name": "Christopher",
        "last_name": "Lane",
        "email": "christopher.lane@metropolitanlivingpartners.com",
        "company": "Metropolitan Living Partners",
        "job_title": "VP of Resident Services",
        "phone": "+1-212-555-0835",
        "city": "New York",
        "state": "NY",
        "country": "United States",
        "status": "new",
        "notes": "Urban multifamily operator with 13,200 units across New York, Boston, and Washington DC. Renewal rate dropped from 61% to 54% post-pandemic and has not recovered despite multiple manual campaigns. Currently running a call center renewal program with 12 agents — cost is high and results are inconsistent. COO has mandated a 5-point improvement in renewal rate by Q4 or the call center program will be restructured. VP sees AI-automated personalized renewal outreach as the primary lever. Urgency is high — Q4 is six months away and he needs to show early indicators in 90 days.",
    },
    {
        "first_name": "Samantha",
        "last_name": "Price",
        "email": "samantha.price@ridgelineresidential.com",
        "company": "Ridgeline Residential",
        "job_title": "Head of Leasing Technology",
        "phone": "+1-404-555-0946",
        "city": "Atlanta",
        "state": "GA",
        "country": "United States",
        "status": "new",
        "notes": "Manages leasing technology stack for 8,700 units in the Atlanta metro. Currently in final vendor evaluation between Domino AI and a competitor called LeaseFlow AI. LeaseFlow AI is priced lower but requires a middleware layer for their Yardi integration — Samantha's team flagged this as a potential point of failure after a bad middleware experience with a previous vendor. Wants to confirm Domino AI's native Yardi API integration is direct with no middleware before making her final recommendation to the VP of Operations. Decision expected within three weeks. Samantha makes the recommendation, VP has final approval.",
    },
    {
        "first_name": "Marcus",
        "last_name": "Caldwell",
        "email": "marcus.caldwell@evergreenresidentialgroup.com",
        "company": "Evergreen Residential Group",
        "job_title": "Regional Vice President",
        "phone": "+1-720-555-0157",
        "city": "Denver",
        "state": "CO",
        "country": "United States",
        "status": "new",
        "notes": "Regional VP overseeing 6,400 units across Denver, Salt Lake City, and Boise with 18 community managers each running their own leasing processes. Corporate compliance audit showed leasing protocol adherence at 42% — community managers are using personal email templates, inconsistent follow-up cadences, and different CRM hygiene standards. Regional VP needs a platform that enforces consistent AI-generated outreach templates, tracks adherence across all 18 communities, and produces a weekly compliance report for corporate. Standardization is the primary requirement; AI quality is secondary to consistency and reporting.",
    },
    {
        "first_name": "Lauren",
        "last_name": "Park",
        "email": "lauren.park@greyfieldcapital.com",
        "company": "Greyfield Capital Partners",
        "job_title": "Director of Innovation",
        "phone": "+1-212-555-0268",
        "city": "New York",
        "state": "NY",
        "country": "United States",
        "status": "new",
        "notes": "Corporate innovation role at a national operator with 25,000 units. Pilot program budget of $150,000 approved for H2 to evaluate AI applications across leasing, operations, and resident experience simultaneously. Interested in a leasing automation pilot covering five properties across two markets with a documented ROI methodology. Results will be presented to the board in Q4. Needs the pilot to start within 30 days to hit the Q4 presentation timeline. Wants a named Domino AI project manager, weekly reporting on pilot metrics, and a defined success scorecard agreed before kickoff. High-visibility project with CEO sponsorship.",
    },
]
