SEED_LEADS = [
    {
        "first_name": "Sarah",
        "last_name": "Chen",
        "email": "sarah.chen@greystoneresidential.com",
        "company": "Greystone Residential Partners",
        "job_title": "VP of Operations",
        "phone": "+1-512-555-0142",
        "city": "Austin",
        "state": "TX",
        "country": "United States",
        "status": "new",
        "notes": "Manages a portfolio of 8,200 units across Central Texas; currently using a manual spreadsheet-based leasing pipeline and mentioned she's losing deals because follow-up times are too slow. Expressed strong interest in automating lead qualification.",
    },
    {
        "first_name": "Marcus",
        "last_name": "Johnson",
        "email": "marcus.johnson@collegiatelivinggroup.com",
        "company": "Collegiate Living Group",
        "job_title": "Director of Leasing",
        "phone": "+1-704-555-0278",
        "city": "Charlotte",
        "state": "NC",
        "country": "United States",
        "status": "new",
        "notes": "Oversees leasing for 12 student housing properties with roughly 4,500 beds; seasonal demand spikes in spring create overwhelming inbound volume his team cannot handle manually. Looking for tools to triage and prioritize leads automatically.",
    },
    {
        "first_name": "Jennifer",
        "last_name": "Patel",
        "email": "jennifer.patel@summitcrestpm.com",
        "company": "Summit Crest Property Management",
        "job_title": "Chief Operating Officer",
        "phone": "+1-602-555-0319",
        "city": "Phoenix",
        "state": "AZ",
        "country": "United States",
        "status": "new",
        "notes": "Regional PM firm with 5,600 units in the Phoenix metro; COO is consolidating three legacy platforms into one and evaluating AI-native solutions. She mentioned her biggest pain point is CRM data hygiene — reps are not updating HubSpot consistently.",
    },
    {
        "first_name": "David",
        "last_name": "Rodriguez",
        "email": "david.rodriguez@communityfirsthousing.org",
        "company": "CommunityFirst Affordable Housing",
        "job_title": "Head of Revenue Operations",
        "phone": "+1-404-555-0453",
        "city": "Atlanta",
        "state": "GA",
        "country": "United States",
        "status": "new",
        "notes": "Nonprofit managing 3,100 affordable housing units across Georgia; tight budget constraints but significant pressure from board to improve leasing velocity. Mentioned they are exploring grant-funded technology initiatives to offset software costs.",
    },
    {
        "first_name": "Emily",
        "last_name": "Thornton",
        "email": "emily.thornton@nexuslivingtechnologies.com",
        "company": "NexusLiving Technologies",
        "job_title": "VP of Technology",
        "phone": "+1-206-555-0587",
        "city": "Seattle",
        "state": "WA",
        "country": "United States",
        "status": "new",
        "notes": "PropTech operator running a tech-enabled property management platform; their internally built lead routing system is struggling to scale past 2,000 concurrent leads. Wants to evaluate off-the-shelf AI orchestration before committing to further in-house development.",
    },
    {
        "first_name": "Robert",
        "last_name": "Kim",
        "email": "robert.kim@landmarkmultifamily.com",
        "company": "Landmark Multifamily REIT",
        "job_title": "Senior VP of Property Management",
        "phone": "+1-312-555-0634",
        "city": "Chicago",
        "state": "IL",
        "country": "United States",
        "status": "new",
        "notes": "Publicly traded multifamily REIT with 22,000 units in 14 markets; procurement process is lengthy but SVP has executive sponsorship for AI tooling initiatives in Q3. Currently using Yardi Voyager and Salesforce; interested in integrations.",
    },
    {
        "first_name": "Amanda",
        "last_name": "Foster",
        "email": "amanda.foster@brightpathseniorliving.com",
        "company": "BrightPath Senior Living",
        "job_title": "Director of Resident Experience",
        "phone": "+1-720-555-0712",
        "city": "Denver",
        "state": "CO",
        "country": "United States",
        "status": "new",
        "notes": "Senior living operator with 18 communities and 2,800 units; family-facing inquiries require high-touch follow-up and the team is dropping leads during peak inquiry windows. Mentioned that automating initial outreach drafts would free up counselors for high-value conversations.",
    },
    {
        "first_name": "Tyler",
        "last_name": "Williams",
        "email": "tyler.williams@pinnaclepropertygroup.com",
        "company": "Pinnacle Property Group",
        "job_title": "Manager of Leasing Operations",
        "phone": "+1-615-555-0891",
        "city": "Nashville",
        "state": "TN",
        "country": "United States",
        "status": "new",
        "notes": "Regional operator managing 3,400 units in the Nashville MSA; leasing team of 11 reps currently manually entering leads from ILS platforms into their CRM. Manager wants to eliminate duplicate data entry and speed up the guest card to application conversion rate.",
    },
    {
        "first_name": "Rachel",
        "last_name": "Nguyen",
        "email": "rachel.nguyen@harborviewreit.com",
        "company": "Harborview Residential REIT",
        "job_title": "VP of Asset Management",
        "phone": "+1-212-555-0964",
        "city": "New York",
        "state": "NY",
        "country": "United States",
        "status": "new",
        "notes": "REIT with 14,500 units in coastal markets including NYC, Boston, and Miami; asset management team evaluates vendor tools on a 12-month budget cycle. VP noted they recently renewed their Entrata contract but have flexibility to add point solutions for AI-driven leasing intelligence.",
    },
    {
        "first_name": "James",
        "last_name": "Callahan",
        "email": "james.callahan@collegiatecommunities.com",
        "company": "Collegiate Communities Inc",
        "job_title": "Chief Revenue Officer",
        "phone": "+1-214-555-0135",
        "city": "Dallas",
        "state": "TX",
        "country": "United States",
        "status": "new",
        "notes": "Student housing operator with 7,000 beds across 9 universities; CRO is building out a revenue operations function from scratch and needs a foundational GTM stack. Mentioned that conversion rate from inquiry to lease is their primary KPI this year.",
    },
    {
        "first_name": "Michelle",
        "last_name": "Lee",
        "email": "michelle.lee@cornerstoneresidentialservices.com",
        "company": "Cornerstone Residential Services",
        "job_title": "Director of Operations",
        "phone": "+1-813-555-0247",
        "city": "Tampa",
        "state": "FL",
        "country": "United States",
        "status": "new",
        "notes": "Third-party property management firm overseeing 6,800 units for 12 owner clients; clients are requesting AI-enhanced reporting and leasing performance dashboards. Director is under contract renewal pressure and positioning new tech adoption as a differentiator.",
    },
    {
        "first_name": "Brandon",
        "last_name": "Scott",
        "email": "brandon.scott@apexstudenthousing.com",
        "company": "Apex Student Housing",
        "job_title": "Head of Leasing Strategy",
        "phone": "+1-512-555-0382",
        "city": "Austin",
        "state": "TX",
        "country": "United States",
        "status": "new",
        "notes": "Student housing operator with 4,200 beds anchored near UT Austin and Texas A&M; pre-leasing season starts in January and the team is already behind on outreach to returning residents. Wants automated personalized outreach campaigns segmented by unit type and lease expiration.",
    },
    {
        "first_name": "Laura",
        "last_name": "Martinez",
        "email": "laura.martinez@southwestpropertyadvisors.com",
        "company": "Southwest Property Advisors",
        "job_title": "VP of Business Development",
        "phone": "+1-480-555-0416",
        "city": "Phoenix",
        "state": "AZ",
        "country": "United States",
        "status": "new",
        "notes": "Consulting firm that manages onboarding for new property management clients across the Southwest; VP is evaluating AI tools to include in their standard client tech stack recommendation. Urgency created by a large client award expected to close within 60 days.",
    },
    {
        "first_name": "Kevin",
        "last_name": "Park",
        "email": "kevin.park@blueskyproperty.com",
        "company": "BlueSky Property Solutions",
        "job_title": "Director of Digital Transformation",
        "phone": "+1-713-555-0558",
        "city": "Houston",
        "state": "TX",
        "country": "United States",
        "status": "new",
        "notes": "Full-service property management company with 9,100 units across Texas and Oklahoma; Director is midway through a two-year digital transformation roadmap. Has already implemented RealPage AI Pricing but identified leasing workflow automation as the next major initiative.",
    },
    {
        "first_name": "Natalie",
        "last_name": "Brooks",
        "email": "natalie.brooks@midtownmultifamily.com",
        "company": "Midtown Multifamily Group",
        "job_title": "Manager of CRM and Revenue Operations",
        "phone": "+1-612-555-0673",
        "city": "Minneapolis",
        "state": "MN",
        "country": "United States",
        "status": "new",
        "notes": "Boutique operator with 1,800 units in Class A Minneapolis properties; CRM manager is consolidating Salesforce and Knock into a single source of truth. Looking for AI that can write first-draft outreach emails from structured lead data without requiring sales rep input.",
    },
    {
        "first_name": "Steven",
        "last_name": "Walsh",
        "email": "steven.walsh@evergreenaffordable.org",
        "company": "Evergreen Affordable Living",
        "job_title": "Chief Financial Officer",
        "phone": "+1-303-555-0794",
        "city": "Denver",
        "state": "CO",
        "country": "United States",
        "status": "new",
        "notes": "Nonprofit managing 2,400 affordable and workforce housing units in Colorado; CFO is exploring cost-reduction tools as Section 8 administrative burden has increased significantly. Interested in automation that reduces manual compliance reporting overhead.",
    },
    {
        "first_name": "Diana",
        "last_name": "Torres",
        "email": "diana.torres@pacificcoastrealtygroup.com",
        "company": "Pacific Coast Realty Group",
        "job_title": "Director of Resident Marketing",
        "phone": "+1-858-555-0829",
        "city": "San Diego",
        "state": "CA",
        "country": "United States",
        "status": "new",
        "notes": "Property management arm of a coastal California real estate firm with 4,700 units; Director oversees all resident acquisition marketing and is frustrated with low email open rates from generic outreach templates. Wants AI-personalized messaging at the unit and neighborhood level.",
    },
    {
        "first_name": "Aaron",
        "last_name": "Mitchell",
        "email": "aaron.mitchell@cityscapelivingreit.com",
        "company": "Cityscape Living REIT",
        "job_title": "VP of Resident Success",
        "phone": "+1-404-555-0947",
        "city": "Atlanta",
        "state": "GA",
        "country": "United States",
        "status": "new",
        "notes": "Multifamily REIT with 11,300 units concentrated in Sunbelt markets; VP is building a resident retention program and believes proactive outreach automation is key to reducing 30-day notice attrition. Currently tracking renewal intent manually via spreadsheet.",
    },
    {
        "first_name": "Catherine",
        "last_name": "Reed",
        "email": "catherine.reed@urbanedgemanagement.com",
        "company": "Urban Edge Management",
        "job_title": "Head of Property Technology",
        "phone": "+1-702-555-0163",
        "city": "Las Vegas",
        "state": "NV",
        "country": "United States",
        "status": "new",
        "notes": "Property management firm operating 6,200 units across Nevada and Utah; Head of PropTech oversees vendor selection and recently decommissioned AppFolio in favor of Yardi. Evaluating AI leasing assistants and wants API-first platforms that integrate with their existing stack.",
    },
    {
        "first_name": "William",
        "last_name": "Zhang",
        "email": "william.zhang@heritageluxuryapts.com",
        "company": "Heritage Luxury Apartments",
        "job_title": "Chief Executive Officer",
        "phone": "+1-615-555-0284",
        "city": "Nashville",
        "state": "TN",
        "country": "United States",
        "status": "new",
        "notes": "Boutique luxury apartment operator with 800 units across four high-end Nashville properties; CEO is personally involved in leasing strategy and wants concierge-quality AI-generated outreach that matches the brand's premium positioning. Budget is not a constraint.",
    },
]
